version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: spotify_postgres
    restart: always
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass
      POSTGRES_DB: spotify_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: spotify_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
